### PR TITLE
Update template to USWDS 3

### PR DESCRIPTION
**Pull request by caleywoods**
This is a full changeover to [USWDS 3](https://designsystem.digital.gov/whats-new/updates/2022/04/28/introducing-uswds-3-0/). More work should happen starting from here to identify exactly what components of USWDS the template is using (things like `usa-accordian`, `usa-banner`, etc) so that `styles/styles.scss` can be updated and those individual components can be included rather than the "kitchen sink" approach that I'm using here by pulling in all of USWDS.

I recently used this template for the TTS website project and completed the update to USWDS 3 there and have been using for almost a month and it seems to be working very well.

## Changes proposed in this pull request:
- Updating the template to use USWDS 3

## security considerations
No known security considerations.

### CODE REVIEW

**Comment by caleywoods** [comment]
[You can see a preview build of this branch](https://federalist-5f19721a-ba7c-4664-a077-62d0073f5f49.app.cloud.gov/site/caleywoods/pages-uswds-11ty/).

**Comment by caleywoods** [comment]
Bump - Making sure there's nothing else I need to do on my end currently.

**Comment by hursey013** [comment]
Hey @caleywoods 👋 Appreciate you putting this together! I'm new to 11ty (and some of the new USWDS changes), so been checking this out and will let you know if I come across anything that might be an issue. Bear with us while we complete our Federalist -> cloud.gov Pages migration!

**Review by apburnes — APPROVED** [review]
@caleywoods Thank you! Looks great and you are much appreciated.

**Pull request merged**
